CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    fullname VARCHAR(128) NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(128) NOT NULL,
    state VARCHAR(64) NOT NULL,
    zip VARCHAR(32) NOT NULL,
    phone_number VARCHAR(32) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);
