CREATE TABLE tacos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE taco_ingredients (
    taco_id BIGINT NOT NULL,
    ingredient_id VARCHAR(16) NOT NULL,
    PRIMARY KEY (taco_id, ingredient_id),
    CONSTRAINT fk_taco_ingredients_taco
        FOREIGN KEY (taco_id) REFERENCES tacos (id) ON DELETE CASCADE,
    CONSTRAINT fk_taco_ingredients_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients (id)
);

CREATE INDEX idx_taco_ingredients_ingredient_id
    ON taco_ingredients (ingredient_id);

CREATE TABLE order_items (
    order_id BIGINT NOT NULL,
    taco_id BIGINT NOT NULL,
    PRIMARY KEY (order_id, taco_id),
    CONSTRAINT uk_order_items_taco UNIQUE (taco_id),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_taco
        FOREIGN KEY (taco_id) REFERENCES tacos (id)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
